#!/usr/bin/env python3
"""D2 Phase 1.4/1.5: freeze the raw-imputation scoring baseline under the fixed (per-call) RNG,
determinism-assert it, then re-score the committed Phase B six-config table against it (arithmetic
only against already-committed recon_rmse numerators -- no tokenizer retraining).

Frozen scope: GLOBAL_DEV (kgs_dev + nlog_dev), all 11 canonical curves, imputer trained on
kgs_train+nlog_train+force_train, XGBoost params/seed = eval_harness.SEED/XGB (committed).
"""
import hashlib, json, time
from pathlib import Path
import numpy as np
from xgboost import XGBRegressor
import eval_harness as EH

OUT = EH.ROOT / "reports/basinshift"
GLOBAL_TRAIN_POOLS = ["kgs_train", "nlog_train", "force_train"]
GLOBAL_DEV_WELLS = EH.wells_of("kgs", "dev") + EH.wells_of("nlog", "dev")


def grid_for(target):
    """Grid entries carry (wid, valid, y, src, safe) -- src/safe needed directly since dev wells
    are not in EH.POOLS_ALL (that only covers train/test_kgs/open10 pools)."""
    grid = []
    for (src, safe, wid) in GLOBAL_DEV_WELLS:
        df = EH.load_well(src, safe, wid)
        y = df[target].to_numpy()
        valid = np.where(~np.isnan(y))[0]
        if len(valid) < EH.MIN_TARGET_SAMPLES:
            continue
        grid.append((wid, valid, EH.inverse_transform(target, y[valid]), src, safe))
    return grid


def predict_raw(target, model, grid5):
    feats = EH.feats_for(target)
    preds = {}
    for (wid, valid, _y, src, safe) in grid5:
        df = EH.load_well(src, safe, wid)
        X = df[feats].to_numpy()[valid]
        preds[wid] = EH.inverse_transform(target, model.predict(X))
    return preds


def score3(grid5, preds, target):
    grid3 = [(w, v, y) for (w, v, y, s, sf) in grid5]
    return EH.score(grid3, preds, target)


def main():
    t0 = time.time()
    baseline = {}
    for c in EH.CANON:
        print(f"[{c}] asserting determinism...", flush=True)
        EH.assert_build_train_deterministic(GLOBAL_TRAIN_POOLS, c, seed=EH.SEED)
        g = grid_for(c)
        if not g:
            baseline[c] = dict(raw_rmse=None, n_samples=0, n_wells=0, degenerate=True,
                               cause="empty global-dev grid")
            print(f"[{c}] DEGENERATE empty grid")
            continue
        Xtr, ytr = EH.build_train(GLOBAL_TRAIN_POOLS, c, seed=EH.SEED)
        m = XGBRegressor(**EH.XGB)
        m.fit(Xtr, ytr)
        preds = predict_raw(c, m, g)
        sc = score3(g, preds, c)
        rr = sc["pooled_rmse"]
        degen = (rr is None) or (not np.isfinite(rr)) or (rr < 1e-6)
        baseline[c] = dict(raw_rmse=rr, n_samples=sc["n_samples"], n_wells=sc["n_wells"],
                           degenerate=bool(degen), cause=None)
        print(f"[{c}] raw_rmse={rr:.6f} n={sc['n_samples']} wells={sc['n_wells']} "
              f"elapsed={time.time()-t0:.0f}s", flush=True)

    artifact = dict(
        frozen_at="D2 Phase 1 (2026-07-25)",
        imputer_seed=EH.SEED,
        xgb_params={k: v for k, v in EH.XGB.items()},
        train_pools=GLOBAL_TRAIN_POOLS,
        dev_pools=["kgs_dev", "nlog_dev"],
        canon_curves=EH.CANON,
        determinism_asserted=True,
        note=("Frozen raw-imputation baseline under the FIXED per-call rng "
              "(D2 Phase 1 defect fix). Denominator and imputer seed frozen together per D4. "
              "Does NOT reproduce the original committed baseline_results.json -- that artifact "
              "was generated by basinshift_baseline.py, which has the identical module-level "
              "shared-rng defect (confirmed by direct code read), and is order-dependent on its "
              "own internal call sequence. This frozen artifact is order-independent and "
              "reproducible by construction (see determinism_asserted); it supersedes Phase B's "
              "and D1's un-frozen, run-dependent raw_rmse values as the reference denominator "
              "going forward, but is NOT claimed to match baseline_results.json."),
        baseline=baseline,
    )
    payload = json.dumps(artifact, indent=2, sort_keys=True)
    out_path = OUT / "frozen_raw_baseline_2026-07-25.json"
    out_path.write_text(payload)
    sha = hashlib.sha256(payload.encode()).hexdigest()
    (OUT / "frozen_raw_baseline_2026-07-25.sha256").write_text(sha + "\n")
    print(f"\nFROZEN BASELINE WRITTEN: {out_path}")
    print(f"sha256: {sha}")
    print(f"total elapsed: {time.time()-t0:.0f}s")
    return baseline, sha


if __name__ == "__main__":
    main()
